name: tldr
version: 0.0.2
description: >
  A simple client for tldr, a collection of simplified man pages.
author: Harry Terkelsen <harry@terkelsen.io>
homepage: https://github.com/hterkelsen/tldr

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  http: ^0.12.0+4
  path: ^1.6.4

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0

executables:
  tldr:
